const mongoose = require('mongoose')
const Schema = mongoose.Schema

const schema = new Schema({
    object: String,
    id: String,
    oracle_id: String,
    multiverse_ids: Array,
    name: String,
    lang: String,
    released_at: String,
    uri: String,
    scryfall_uri: String,
    layout: String,
    highres_image: Boolean,
    image_uris: [{
        small: String,
        normal: String,
        large: String,
        png: String,
        art_crop: String,
        border_crop: String,
    }],
    mana_cost: String,
    cmc: Number,
    type_line: String,
    oracle_text: String,
    colors: Array,
    color_identity: Array,
    legalities: [{
        standard: String,
        future: String,
        frontier: String,
        modern: String,
        legacy: String,
        pauper: String,
        vintage: String,
        penny: String,
        commander: String,
        v1: String,
        duel: String,
        brawl: String,
    }],
    games: Array,
    reserved: Boolean,
    foil: Boolean,
    nonfoil: Boolean,
    oversized: Boolean,
    promo: Boolean,
    reprint: Boolean,
    set: String,
    set_name: String,
    set_uri: String,
    set_search_uri: String,
    scryfall_set_uri: String,
    rulings_uri: String,
    prints_search_uri: String,
    collector_number: String,
    digital: Boolean,
    rarity: String,
    watermark: String,
    illustration_id: String,
    artist: String,
    border_color: String,
    frame: String,
    frame_effect: String,
    full_art: Boolean,
    timeshifted: Boolean,
    colorshifted: Boolean,
    futureshifted: Boolean,
    story_spotlight: Boolean,
    related_uris: [{
        gatherer: String,
        tcgplayer_decks: String,
        edhrec: String,
        mtgtop8: String,
    }],
    power: String,
    toughness: String,
    flavor_text: String,
    tcgplayer_id: Number,
    card_faces: Array,
    edhrec_rank: Number,
    all_parts: Array
}, { collection: "Set" });

const Card_All = mongoose.model('Set', schema);

module.exports = Card_All;